{% set name = "sctour" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e3d1327518c5c94283ba6c1112e5ef72739a91f45670744e93af701ec41d9413

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pytorch >=1.9.1
    - torchdiffeq >=0.2.2
    - numpy >=1.19.2
    - scanpy >=1.7.1
    - python >=3.7
    - anndata >=0.7.5
    - scipy >=1.5.2
    - tqdm >=4.32.2
    - scikit-learn >=0.24.1
    - leidenalg >=0.8.4

test:
  imports:
    - sctour

about:
  home: "https://github.com/LiQian-XC/sctour"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A deep learning architecture for robust inference and accurate prediction of cellular dynamics"
  dev_url: "https://github.com/LiQian-XC/sctour"
  doc_url: "https://github.com/LiQian-XC/sctour"

extra:
  recipe-maintainers:
      - LiQian-XC
